'use client'
import Footer from '../components/Footer'
import AvantiLogo from '../components/AvantiLogo'

export default function TermsOfService() {
  const s = { fontFamily: 'var(--font-cormorant), Georgia, serif' }
  return (
    <div style={{ minHeight: '100vh', background: '#fafaf8', display: 'flex', flexDirection: 'column', ...s }}>
      <div style={{ maxWidth: '720px', margin: '0 auto', padding: '48px 24px', flex: 1 }}>
        <div style={{ marginBottom: '40px' }}>
          <AvantiLogo size="sm" />
        </div>
        <p style={{ fontSize: '11px', letterSpacing: '0.2em', textTransform: 'uppercase', color: '#9a9a8a', margin: '0 0 12px' }}>Legal</p>
        <h1 style={{ fontSize: '40px', fontWeight: 300, color: '#083807', margin: '0 0 8px', ...s }}>Terms of Service</h1>
        <p style={{ fontSize: '13px', color: '#9a9a8a', margin: '0 0 48px' }}>Last updated: June 2026</p>

        {[
          { title: 'Acceptance of terms', content: 'By creating an account and using Avanti, you agree to these Terms of Service. If you do not agree, please do not use Avanti.' },
          { title: 'What Avanti is', content: 'Avanti is a group travel planning tool that uses AI to help groups organize trips. Avanti provides travel suggestions, cost estimates, and coordination tools. Avanti is not a travel agency, booking platform, or licensed travel advisor. All travel suggestions and cost estimates are for informational purposes only and are not guaranteed to be accurate.' },
          { title: 'Your account', content: 'You are responsible for keeping your account credentials secure. You must be at least 18 years old to create an account. You agree to provide accurate information when creating your account and to keep it up to date.' },
          { title: 'Acceptable use', content: 'You agree to use Avanti only for lawful purposes and in accordance with these terms. You may not use Avanti to harass other users, share false information, or attempt to gain unauthorized access to any part of the service.' },
          { title: 'Travel information disclaimer', content: 'The travel recommendations, cost estimates, and itinerary suggestions provided by Avanti are generated by AI and are for planning purposes only. Prices, availability, visa requirements, and travel conditions change frequently. Always verify information independently before making bookings or travel decisions. Avanti is not responsible for any losses or damages arising from reliance on AI-generated travel information.' },
          { title: 'User content', content: 'You retain ownership of any content you submit to Avanti, including trip names, messages, and preferences. By submitting content, you grant Avanti a limited license to use that content to provide the service.' },
          { title: 'Privacy', content: 'Your use of Avanti is also governed by our Privacy Policy, which is incorporated into these terms by reference.' },
          { title: 'Termination', content: 'We reserve the right to suspend or terminate your account at any time for violation of these terms or for any other reason at our discretion. You may delete your account at any time from your account settings.' },
          { title: 'Limitation of liability', content: 'To the maximum extent permitted by law, Avanti and its founders are not liable for any indirect, incidental, or consequential damages arising from your use of the service. Our total liability to you for any claims arising from your use of Avanti is limited to the amount you paid us in the past twelve months.' },
          { title: 'Changes to these terms', content: 'We may update these terms from time to time. We will notify you of significant changes by email. Your continued use of Avanti after changes take effect constitutes your acceptance of the updated terms.' },
          { title: 'Contact', content: 'For questions about these terms, email legal@avanti.app.' },
        ].map(section => (
          <div key={section.title} style={{ marginBottom: '36px' }}>
            <h2 style={{ fontSize: '20px', fontWeight: 400, color: '#083807', margin: '0 0 10px', ...s }}>{section.title}</h2>
            <p style={{ fontSize: '14px', color: '#3a3a3a', margin: 0, lineHeight: 1.8 }}>{section.content}</p>
          </div>
        ))}
      </div>
      <Footer />
    </div>
  )
}
