/** Discrete, generic form placeholders — no real names or personal examples. */

export const PLACEHOLDERS = {
  fullName: 'John Smith',
  email: 'you@example.com',
  phone: '555 123 4567',
  nickname: 'John',
  nicknameExamples: 'Em, Jo, Sam…',
  companionName: 'Jane Smith',
  companionNickname: 'Jane',
  companionRelation: 'Partner, friend, family…',
  apartment: 'Apt 4B',
  passport: 'A12345678',
  tsaKnownTraveler: '123456789',
  globalEntry: '123456789',
  loyaltyAccount: '1234567',
  homeAirport: 'ORD — Chicago O\'Hare',
  backupAirports: 'MDW, MKE',
  tripDescription: 'e.g. A weekend trip with friends',
  destination: 'e.g. Lisbon, Portugal',
  departureCity: 'Type a city…',
  dealBreakers: 'e.g. No long layovers, need wheelchair access…',
  tripNameHelper: 'e.g. Summer trip with friends',
  eventName: 'e.g. Wedding weekend',
  eventLocation: 'e.g. Chicago, IL',
  diningArea: 'e.g. near downtown',
  diningDiet: 'e.g. 2 vegetarian',
  diningStyle: 'e.g. Italian, casual',
  expenseDesc: 'Dinner, hotel, taxi…',
  walletCard: 'Visa ending 4242',
  walletHandle: '@username',
  inviteEmail: 'friend@example.com',
  chatAsk: 'Ask Avanti anything about this trip…',
  flightChat: 'Ask for more options…',
} as const
